#
# Copyright (C) 2019 The LineageOS Project
# Copyright (C) 2022 ComicoX
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

_output_file=$2
function header() {
    sed -i "1s|^|$1\n|" $_output_file
}

BUILD_FINGERPRINT="11/RKQ1.200710.002/30.41.69.143_20211222:user/release-keys"

# Load extract_utils and do some sanity checks
MY_DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$MY_DIR" ]]; then MY_DIR="$PWD"; fi

ANDROID_ROOT="${MY_DIR}/../../.."

HELPER="${ANDROID_ROOT}/tools/extract-utils/extract_utils.sh"
if [ ! -f "$HELPER" ]; then
    echo "Unable to find helper script at $HELPER"
    exit 1
fi
. "$HELPER"

if [ -z "$1" ]; then
    echo "No input image supplied"
    exit 1
fi

if [ -z "$2" ]; then
    echo "No output filename supplied"
    exit 1
fi

VENDOR_SKIP_FILES_DEVICE=(
    # Asus setenforce
    "bin/init.asus.check_asdf.sh"
    "bin/init.asus.check_last.sh"
    "bin/savelogmtp.sh"
    "bin/savelogs.sh"
    "bin/shipping_rework.sh"
    "bin/triggerpanic.sh"
    "bin/widevine.sh"
    "etc/init/hw/init.asus.debugtool.rc"
    "etc/init/init.asus.shippingrework.rc"

    # Audio
    # Use prebuilt audio.primary.kona
    # "lib/hw/audio.primary.kona.so"
    # "lib/liba2dpoffload.so"
    # "lib64/hw/audio.primary.kona.so"
    # "lib64/liba2dpoffload.so"
    #"lib/hw/sound_trigger.primary.kona.so"
    #"lib64/hw/sound_trigger.primary.kona.so"
    "bin/hw/android.hardware.audio.service"
    "etc/init/android.hardware.audio.service.rc"
    "lib/android.hardware.audio.common-util.so"
    "lib/android.hardware.audio.common@2.0-util.so"
    "lib/android.hardware.audio.common@4.0-util.so"
    "lib/android.hardware.audio.common@5.0-util.so"
    "lib/android.hardware.audio.common@6.0-util.so"
    "lib/hw/android.hardware.audio.effect@2.0-impl.so"
    "lib/hw/android.hardware.audio.effect@4.0-impl.so"
    "lib/hw/android.hardware.audio.effect@5.0-impl.so"
    "lib/hw/android.hardware.audio.effect@6.0-impl.so"
    "lib/hw/android.hardware.audio@2.0-impl.so"
    "lib/hw/android.hardware.audio@4.0-impl.so"
    "lib/hw/android.hardware.audio@5.0-impl.so"
    "lib/hw/android.hardware.audio@6.0-impl.so"
    "lib/hw/android.hardware.bluetooth.audio@2.0-impl.so"
    "lib/hw/android.hardware.soundtrigger@2.1-impl.so"
    "lib/hw/android.hardware.soundtrigger@2.2-impl.so"
    "lib/hw/audio.bluetooth.default.so"
    "lib/hw/audio.r_submix.default.so"
    "lib/hw/audio.usb.default.so"
    "lib/libalsautils.so"
    "lib/libbluetooth_audio_session.so"
    "lib/libcirrusspkrprot.so"
    "lib/libcomprcapture.so"
    "lib/libexthwplugin.so"
    "lib/libhdmiedid.so"
    "lib/libhfp.so"
    "lib/libnbaio_mono.so"
    "lib/libsndmonitor.so"
    "lib/libspkrprot.so"
    "lib/libtinycompress.so"
    "lib64/android.hardware.audio.common-util.so"
    "lib64/android.hardware.audio.common@2.0-util.so"
    "lib64/android.hardware.audio.common@4.0-util.so"
    "lib64/android.hardware.audio.common@5.0-util.so"
    "lib64/android.hardware.audio.common@6.0-util.so"
    "lib64/hw/android.hardware.audio.effect@2.0-impl.so"
    "lib64/hw/android.hardware.audio.effect@4.0-impl.so"
    "lib64/hw/android.hardware.audio.effect@5.0-impl.so"
    "lib64/hw/android.hardware.audio.effect@6.0-impl.so"
    "lib64/hw/android.hardware.audio@2.0-impl.so"
    "lib64/hw/android.hardware.audio@4.0-impl.so"
    "lib64/hw/android.hardware.audio@5.0-impl.so"
    "lib64/hw/android.hardware.audio@6.0-impl.so"
    "lib64/hw/android.hardware.bluetooth.audio@2.0-impl.so"
    "lib64/hw/android.hardware.soundtrigger@2.2-impl.so"
    "lib64/hw/audio.bluetooth.default.so"
    "lib64/hw/audio.r_submix.default.so"
    "lib64/hw/audio.usb.default.so"
    "lib64/libalsautils.so"
    "lib64/libbluetooth_audio_session.so"
    "lib64/libcirrusspkrprot.so"
    "lib64/libcomprcapture.so"
    "lib64/libexthwplugin.so"
    "lib64/libhdmiedid.so"
    "lib64/libhfp.so"
    "lib64/libnbaio_mono.so"
    "lib64/libsndmonitor.so"
    "lib64/libspkrprot.so"
    "lib64/libtinycompress.so"

    # Audio configs
    "etc/audio_policy_configuration.xml"
    "etc/audio/audio_policy_configuration.xml"

    # Biometrics
    # Use prebuild init.rc to write the pid for this service to the correct cpuset
    # "etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc"
    "bin/hw/android.hardware.biometrics.fingerprint@2.1-service"
    "etc/vintf/manifest/android.hardware.biometrics.fingerprint@2.1-service.xml"

    # Bluetooth
    "lib/com.qualcomm.qti.bluetooth_audio@1.0.so"
    "lib/vendor.qti.hardware.bluetooth_audio@2.0.so"
    "lib/vendor.qti.hardware.btconfigstore@1.0.so"
    "lib64/com.qualcomm.qti.bluetooth_audio@1.0.so"
    "lib64/vendor.qti.hardware.bluetooth_audio@2.0.so"
    "lib64/vendor.qti.hardware.btconfigstore@1.0.so"

    # Bootctrl
    "bin/hw/android.hardware.boot@1.1-service"
    "etc/init/android.hardware.boot@1.1-service.rc"
    "etc/vintf/manifest/android.hardware.boot@1.1.xml"
    "lib/hw/android.hardware.boot@1.0-impl-1.1-qti.so"
    "lib/libboot_control_qti.so"
    "lib64/hw/android.hardware.boot@1.0-impl-1.1-qti.so"
    "lib64/libboot_control_qti.so"

    # Camera
    #"etc/init/android.hardware.camera.provider@2.4-service_64.rc"
    #"bin/hw/android.hardware.camera.provider@2.4-service_64"
    "lib/android.hardware.camera.provider@2.4-external.so"
    "lib/android.hardware.camera.provider@2.4-legacy.so"
    "lib/camera.device@1.0-impl.so"
    "lib/camera.device@3.2-impl.so"
    "lib/camera.device@3.3-impl.so"
    "lib/camera.device@3.4-external-impl.so"
    "lib/camera.device@3.4-impl.so"
    "lib/camera.device@3.5-external-impl.so"
    "lib/camera.device@3.5-impl.so"
    "lib/camera.device@3.6-external-impl.so"
    "lib/hw/android.hardware.camera.provider@2.4-impl.so"
    "lib/vendor.qti.hardware.camera.device@1.0.so"
    "lib/vendor.qti.hardware.camera.postproc@1.0.so"
    "lib64/android.hardware.camera.provider@2.4-external.so"
    "lib64/android.hardware.camera.provider@2.4-legacy.so"
    "lib64/camera.device@1.0-impl.so"
    "lib64/camera.device@3.2-impl.so"
    "lib64/camera.device@3.3-impl.so"
    "lib64/camera.device@3.4-external-impl.so"
    "lib64/camera.device@3.4-impl.so"
    "lib64/camera.device@3.5-external-impl.so"
    "lib64/camera.device@3.5-impl.so"
    "lib64/camera.device@3.6-external-impl.so"
    "lib64/hw/android.hardware.camera.provider@2.4-impl.so"
    "lib64/vendor.qti.hardware.camera.device@1.0.so"
    "lib64/vendor.qti.hardware.camera.postproc@1.0.so"

    # config.fs
    "etc/fs_config_dirs"
    "etc/fs_config_files"
    "etc/group"
    "etc/passwd"

    # Display
    # Use prebuilt composer for PixelWorks Iris
    # "bin/hw/vendor.qti.hardware.display.composer-service"
    # "lib/libsdedrm.so"
    # "lib/libsdmcore.so"
    # "lib/libsdmutils.so"
    # "lib64/libsdedrm.so"
    # "lib64/libsdmcore.so"
    # "lib64/libsdmutils.so"
    "bin/hw/android.hardware.memtrack@1.0-service"
    "bin/hw/vendor.qti.hardware.display.allocator-service"
    "etc/init/android.hardware.memtrack@1.0-service.rc"
    "etc/init/vendor.qti.hardware.display.allocator-service.rc"
    "etc/init/vendor.qti.hardware.display.composer-service.rc"
    "etc/vintf/manifest/android.hardware.graphics.mapper-impl-qti-display.xml"
    "etc/vintf/manifest/vendor.qti.hardware.display.allocator-service.xml"
    "etc/vintf/manifest/vendor.qti.hardware.display.composer-service.xml"
    "lib/hw/android.hardware.graphics.mapper@3.0-impl-qti-display.so"
    "lib/hw/android.hardware.graphics.mapper@4.0-impl-qti-display.so"
    "lib/hw/android.hardware.memtrack@1.0-impl.so"
    "lib/hw/android.hardware.renderscript@1.0-impl.so"
    "lib/hw/gralloc.kona.so"
    "lib/hw/lights.kona.so"
    "lib/hw/memtrack.kona.so"
    "lib/libdisplayconfig.qti.so"
    "lib/libdisplaydebug.so"
    "lib/libdrm.so"
    "lib/libdrmutils.so"
    "lib/libgralloc.qti.so"
    "lib/libgralloccore.so"
    "lib/libgrallocutils.so"
    "lib/libqdMetaData.so"
    "lib/libqdutils.so"
    "lib/libqservice.so"
    "lib/libtinyxml.so"
    "lib/vendor.display.config@1.0.so"
    "lib/vendor.display.config@1.1.so"
    "lib/vendor.display.config@1.10.so"
    "lib/vendor.display.config@1.11.so"
    "lib/vendor.display.config@1.2.so"
    "lib/vendor.display.config@1.3.so"
    "lib/vendor.display.config@1.4.so"
    "lib/vendor.display.config@1.5.so"
    "lib/vendor.display.config@1.6.so"
    "lib/vendor.display.config@1.7.so"
    "lib/vendor.display.config@1.8.so"
    "lib/vendor.display.config@1.9.so"
    "lib/vendor.display.config@2.0.so"
    "lib/vendor.qti.hardware.display.allocator@1.0.so"
    "lib/vendor.qti.hardware.display.allocator@3.0.so"
    "lib/vendor.qti.hardware.display.composer@1.0.so"
    "lib/vendor.qti.hardware.display.composer@2.0.so"
    "lib/vendor.qti.hardware.display.mapper@1.0.so"
    "lib/vendor.qti.hardware.display.mapper@1.1.so"
    "lib/vendor.qti.hardware.display.mapper@2.0.so"
    "lib/vendor.qti.hardware.display.mapper@3.0.so"
    "lib/vendor.qti.hardware.display.mapper@4.0.so"
    "lib/vendor.qti.hardware.display.mapperextensions@1.0.so"
    "lib/vendor.qti.hardware.display.mapperextensions@1.1.so"
    "lib64/hw/android.hardware.graphics.mapper@3.0-impl-qti-display.so"
    "lib64/hw/android.hardware.graphics.mapper@4.0-impl-qti-display.so"
    "lib64/hw/android.hardware.memtrack@1.0-impl.so"
    "lib64/hw/android.hardware.renderscript@1.0-impl.so"
    "lib64/hw/gralloc.kona.so"
    "lib64/hw/lights.kona.so"
    "lib64/hw/memtrack.kona.so"
    "lib64/libdisplayconfig.qti.so"
    "lib64/libdisplaydebug.so"
    "lib64/libdrm.so"
    "lib64/libdrmutils.so"
    "lib64/libgpu_tonemapper.so"
    "lib64/libgralloc.qti.so"
    "lib64/libgralloccore.so"
    "lib64/libgrallocutils.so"
    "lib64/libhistogram.so"
    "lib64/libqdMetaData.so"
    "lib64/libqdutils.so"
    "lib64/libqservice.so"
    "lib64/libtinyxml.so"
    "lib64/vendor.display.config@1.0.so"
    "lib64/vendor.display.config@1.1.so"
    "lib64/vendor.display.config@1.10.so"
    "lib64/vendor.display.config@1.11.so"
    "lib64/vendor.display.config@1.2.so"
    "lib64/vendor.display.config@1.3.so"
    "lib64/vendor.display.config@1.4.so"
    "lib64/vendor.display.config@1.5.so"
    "lib64/vendor.display.config@1.6.so"
    "lib64/vendor.display.config@1.7.so"
    "lib64/vendor.display.config@1.8.so"
    "lib64/vendor.display.config@1.9.so"
    "lib64/vendor.display.config@2.0.so"
    "lib64/vendor.qti.hardware.display.allocator@1.0.so"
    "lib64/vendor.qti.hardware.display.allocator@3.0.so"
    "lib64/vendor.qti.hardware.display.allocator@4.0.so"
    "lib64/vendor.qti.hardware.display.composer@1.0.so"
    "lib64/vendor.qti.hardware.display.composer@2.0.so"
    "lib64/vendor.qti.hardware.display.composer@3.0.so"
    "lib64/vendor.qti.hardware.display.mapper@1.0.so"
    "lib64/vendor.qti.hardware.display.mapper@1.1.so"
    "lib64/vendor.qti.hardware.display.mapper@2.0.so"
    "lib64/vendor.qti.hardware.display.mapper@3.0.so"
    "lib64/vendor.qti.hardware.display.mapper@4.0.so"
    "lib64/vendor.qti.hardware.display.mapperextensions@1.0.so"
    "lib64/vendor.qti.hardware.display.mapperextensions@1.1.so"

    # IPACM
    "bin/ipacm"
    "etc/init/ipacm.rc"
    "etc/IPACM_cfg.xml"
    "lib64/libipanat.so"
    "lib64/liboffloadhal.so"

    # Kernel modules
    "lib/modules/audio_adsp_loader.ko"
    "lib/modules/audio_apr.ko"
    "lib/modules/audio_bolero_cdc.ko"
    "lib/modules/audio_hdmi.ko"
    "lib/modules/audio_machine_kona.ko"
    "lib/modules/audio_mbhc.ko"
    "lib/modules/audio_native.ko"
    "lib/modules/audio_pinctrl_lpi.ko"
    "lib/modules/audio_pinctrl_wcd.ko"
    "lib/modules/audio_platform.ko"
    "lib/modules/audio_q6_notifier.ko"
    "lib/modules/audio_q6_pdr.ko"
    "lib/modules/audio_q6.ko"
    "lib/modules/audio_rx_macro.ko"
    "lib/modules/audio_snd_event.ko"
    "lib/modules/audio_stub.ko"
    "lib/modules/audio_swr_ctrl.ko"
    "lib/modules/audio_swr.ko"
    "lib/modules/audio_tfa9874.ko"
    "lib/modules/audio_tx_macro.ko"
    "lib/modules/audio_usf.ko"
    "lib/modules/audio_va_macro.ko"
    "lib/modules/audio_wcd_core.ko"
    "lib/modules/audio_wcd938x_slave.ko"
    "lib/modules/audio_wcd938x.ko"
    "lib/modules/audio_wcd9xxx.ko"
    "lib/modules/audio_wsa_macro.ko"
    "lib/modules/gspca_main.ko"
    "lib/modules/lcd.ko"
    "lib/modules/llcc_perfmon.ko"
    "lib/modules/modules.alias"
    "lib/modules/modules.dep"
    "lib/modules/modules.load"
    "lib/modules/modules.softdep"
    "lib/modules/mpq-adapter.ko"
    "lib/modules/mpq-dmx-hw-plugin.ko"
    "lib/modules/qca_cld3_qca6390.ko"
    "lib/modules/qca_cld3_qca6490.ko"
    "lib/modules/rdbg.ko"
    "lib/modules/rmnet_perf.ko"
    "lib/modules/rmnet_shs.ko"
    "lib/modules/texfat.ko"
    "lib/modules/tntfs.ko"

    # libhardware
    "lib/hw/audio.primary.default.so"
    "lib/hw/gralloc.default.so"
    "lib/hw/local_time.default.so"
    "lib/hw/power.default.so"
    "lib/hw/vibrator.default.so"
    "lib64/hw/audio.primary.default.so"
    "lib64/hw/gralloc.default.so"
    "lib64/hw/local_time.default.so"
    "lib64/hw/power.default.so"
    "lib64/hw/vibrator.default.so"

    # Media
    "bin/hw/android.hardware.cas@1.2-service"
    "bin/hw/android.hardware.media.omx@1.0-service"
    "bin/init.qti.media.sh"
    "etc/init/android.hardware.cas@1.2-service.rc"
    "etc/init/android.hardware.media.omx@1.0-service.rc"
    "etc/init/init.qti.media.rc"
    "etc/vintf/manifest/android.hardware.cas@1.2-service.xml"
    "lib/libavservices_minijail_vendor.so"
    "lib/libavservices_minijail.so"
    "lib/libc2dcolorconvert.so"
    "lib/libcodec2_hidl@1.0.so"
    "lib/libcodec2_vndk.so"
    "lib/libeffects.so"
    "lib/libeffectsconfig.so"
    "lib/libmm-omxcore.so"
    "lib/libOmxAacEnc.so"
    "lib/libOmxAmrEnc.so"
    "lib/libOmxCore.so"
    "lib/libOmxEvrcEnc.so"
    "lib/libOmxG711Enc.so"
    "lib/libOmxQcelp13Enc.so"
    "lib/libOmxVdec.so"
    "lib/libOmxVenc.so"
    "lib/libopus.so"
    "lib/libplatformconfig.so"
    "lib/libstagefright_amrnb_common.so"
    "lib/libstagefright_bufferpool@2.0.1.so"
    "lib/libstagefright_enc_common.so"
    "lib/libstagefright_flacdec.so"
    "lib/libstagefright_soft_aacdec.so"
    "lib/libstagefright_soft_aacenc.so"
    "lib/libstagefright_soft_amrdec.so"
    "lib/libstagefright_soft_amrnbenc.so"
    "lib/libstagefright_soft_amrwbenc.so"
    "lib/libstagefright_soft_avcdec.so"
    "lib/libstagefright_soft_avcenc.so"
    "lib/libstagefright_soft_flacdec.so"
    "lib/libstagefright_soft_flacenc.so"
    "lib/libstagefright_soft_g711dec.so"
    "lib/libstagefright_soft_gsmdec.so"
    "lib/libstagefright_soft_hevcdec.so"
    "lib/libstagefright_soft_mp3dec.so"
    "lib/libstagefright_soft_mpeg2dec.so"
    "lib/libstagefright_soft_mpeg4dec.so"
    "lib/libstagefright_soft_mpeg4enc.so"
    "lib/libstagefright_soft_opusdec.so"
    "lib/libstagefright_soft_rawdec.so"
    "lib/libstagefright_soft_vorbisdec.so"
    "lib/libstagefright_soft_vpxdec.so"
    "lib/libstagefright_soft_vpxenc.so"
    "lib/libstagefright_softomx_plugin.so"
    "lib/libstagefright_softomx.so"
    "lib/libstagefrighthw.so"
    "lib/libvorbisidec.so"
    "lib/libvpx.so"
    "lib/libwebrtc_audio_preprocessing.so"
    "lib/libwfdaac_vendor.so"
    "lib/mediacas/libclearkeycasplugin.so"
    "lib/mediadrm/libdrmclearkeyplugin.so"
    "lib/soundfx/libaudiopreprocessing.so"
    "lib/soundfx/libbundlewrapper.so"
    "lib/soundfx/libdownmix.so"
    "lib/soundfx/libdynproc.so"
    "lib/soundfx/libeffectproxy.so"
    "lib/soundfx/libldnhncr.so"
    "lib/soundfx/libqcompostprocbundle.so"
    "lib/soundfx/libqcomvisualizer.so"
    "lib/soundfx/libqcomvoiceprocessing.so"
    "lib/soundfx/libreverbwrapper.so"
    "lib/soundfx/libvisualizer.so"
    "lib/soundfx/libvolumelistener.so"
    "lib/vendor.qti.hardware.capabilityconfigstore@1.0.so"
    "lib/vndk/libstagefright_foundation.so"
    "lib/vndk/libstagefright_omx.so"
    "lib64/libavservices_minijail.so"
    "lib64/libc2dcolorconvert.so"
    "lib64/libcodec2_hidl@1.0.so"
    "lib64/libcodec2_vndk.so"
    "lib64/libeffects.so"
    "lib64/libeffectsconfig.so"
    "lib64/libmm-omxcore.so"
    "lib64/libOmxAacEnc.so"
    "lib64/libOmxAmrEnc.so"
    "lib64/libOmxCore.so"
    "lib64/libOmxEvrcEnc.so"
    "lib64/libOmxG711Enc.so"
    "lib64/libOmxQcelp13Enc.so"
    "lib64/libOmxVdec.so"
    "lib64/libOmxVenc.so"
    "lib64/libplatformconfig.so"
    "lib64/libstagefright_bufferpool@2.0.1.so"
    "lib64/libstagefright_softomx.so"
    "lib64/libstagefrighthw.so"
    "lib64/libwebrtc_audio_preprocessing.so"
    "lib64/mediacas/libclearkeycasplugin.so"
    "lib64/mediadrm/libdrmclearkeyplugin.so"
    "lib64/soundfx/libaudiopreprocessing.so"
    "lib64/soundfx/libbundlewrapper.so"
    "lib64/soundfx/libdownmix.so"
    "lib64/soundfx/libdynproc.so"
    "lib64/soundfx/libeffectproxy.so"
    "lib64/soundfx/libldnhncr.so"
    "lib64/soundfx/libqcompostprocbundle.so"
    "lib64/soundfx/libqcomvisualizer.so"
    "lib64/soundfx/libqcomvoiceprocessing.so"
    "lib64/soundfx/libreverbwrapper.so"
    "lib64/soundfx/libvisualizer.so"
    "lib64/soundfx/libvolumelistener.so"
    "lib64/vendor.qti.hardware.capabilityconfigstore@1.0.so"

    # Misc
    "etc/Generic/Launcher/default_workspace/default_allapp.xml"
    "etc/Generic/Launcher/default_workspace/phone_workspace.xml"
    "etc/ID/ASUS/Launcher/default_workspace/default_allapp.xml"
    "etc/ID/ASUS/Launcher/default_workspace/phone_workspace.xml"
    "etc/JP/ACJ/Launcher/default_workspace/default_allapp.xml"
    "etc/JP/ACJ/Launcher/default_workspace/phone_workspace.xml"
    "etc/JP/ASUS/Launcher/default_workspace/default_allapp.xml"
    "etc/JP/ASUS/Launcher/default_workspace/phone_workspace.xml"
    "etc/RU/ASUS/Launcher/default_workspace/default_allapp.xml"
    "etc/RU/ASUS/Launcher/default_workspace/phone_workspace.xml"
    "etc/TW/APTG/Launcher/default_workspace/default_allapp.xml"
    "etc/TW/APTG/Launcher/default_workspace/phone_workspace.xml"
    "etc/TW/ASUS/Launcher/default_workspace/default_allapp.xml"
    "etc/TW/ASUS/Launcher/default_workspace/phone_workspace.xml"
    "etc/US/ASUS/Launcher/default_workspace/default_allapp.xml"
    "etc/US/ASUS/Launcher/default_workspace/phone_workspace.xml"
    "etc/WW/ASUS/Launcher/default_workspace/default_allapp.xml"
    "etc/WW/ASUS/Launcher/default_workspace/phone_workspace.xml"

    # Misc daemons
    "bin/asus_osinfo"
    "bin/netutild"
    "bin/sar_setting"

    # Misc hals
    "bin/hw/vendor.ims.airtrigger@1.2-service"
    "bin/hw/vendor.ims.glovemode@1.0-service"
    "bin/hw/vendor.ims.twinviewdock@1.0-service"
    "bin/hw/vendor.ims.wifiantennamode@1.0-service"
    "bin/hw/vendor.ims.zenmotion@1.0-service"
    "bin/hw/vendor.ozoaudio.media.c2@1.0-service"
    "etc/adbkey.pub"
    "etc/init/vendor.ims.airtrigger@1.2-service.rc"
    "etc/init/vendor.ims.glovemode@1.0-service.rc"
    "etc/init/vendor.ims.twinviewdock@1.0-service.rc"
    "etc/init/vendor.ims.wifiantennamode@1.0-service.rc"
    "etc/init/vendor.ims.zenmotion@1.0-service.rc"
    "etc/init/vendor.ozoaudio.media.c2@1.0-service.rc"
    "lib64/vendor.ims.airtrigger@1.0.so"
    "lib64/vendor.ims.airtrigger@1.1.so"
    "lib64/vendor.ims.airtrigger@1.2.so"
    "lib64/vendor.ims.glovemode@1.0.so"
    "lib64/vendor.ims.twinviewdock@1.0.so"
    "lib64/vendor.ims.wifiantennamode@1.0.so"
    "lib64/vendor.ims.zenmotion@1.0.so"

    # NFC USE PREBUILT NFC
    #"lib/libchrome.so"
    #"lib/vendor.nxp.hardware.nfc@1.0.so"
    #"lib/vendor.nxp.hardware.nfc@1.1.so"
    #"lib64/libchrome.so"
    #"lib64/vendor.nxp.hardware.nfc@1.0.so"
    #"lib64/vendor.nxp.hardware.nfc@1.1.so"

    # Other services
    "bin/hw/android.hardware.atrace@1.0-service"
    "bin/hw/android.hardware.configstore@1.1-service"
    "bin/hw/android.hardware.drm@1.3-service.clearkey"
    "bin/hw/android.hardware.health@2.1-service"
    "bin/hw/android.hardware.thermal@2.0-service.qti"
    "bin/hw/android.hardware.usb@1.2-service-qti"
    "bin/hw/vendor.qti.hardware.servicetracker@1.2-service"
    "bin/hw/vendor.qti.hardware.vibrator.service"
    "etc/excluded-input-devices.xml"
    "etc/init/android.hardware.atrace@1.0-service.rc"
    "etc/init/android.hardware.configstore@1.1-service.rc"
    "etc/init/android.hardware.drm@1.3-service.clearkey.rc"
    "etc/init/android.hardware.health@2.1-service.rc"
    "etc/init/android.hardware.thermal@2.0-service.qti.rc"
    "etc/init/android.hardware.usb@1.2-service-qti.rc"
    "etc/init/netutild.rc"
    "etc/init/vendor.qti.hardware.servicetracker@1.2-service.rc"
    "etc/init/vendor.qti.hardware.vibrator.service.rc"
    "etc/vintf/manifest/android.hardware.atrace@1.0-service.xml"
    "etc/vintf/manifest/android.hardware.health@2.1.xml"
    "etc/vintf/manifest/android.hardware.thermal@2.0-service.qti.xml"
    "etc/vintf/manifest/android.hardware.usb@1.2-service.xml"
    "etc/vintf/manifest/manifest_android.hardware.drm@1.3-service.clearkey.xml"
    "etc/vintf/manifest/vendor.goodix.hardware.biometrics.fingerprint.xml"
    "etc/vintf/manifest/vendor.qti.hardware.servicetracker@1.2-service.xml"
    "etc/vintf/manifest/vendor.qti.hardware.vibrator.service.xml"
    "lib/android.hardware.automotive.vehicle@2.0-manager-lib.so"
    "lib/carwatchdog_aidl_interface-V2-ndk_platform.so"
    "lib/com.dsi.ant@1.0.so"
    "lib/hw/android.hardware.health@2.0-impl-2.1.so"
    "lib/hw/vendor.qti.hardware.servicetracker@1.2-impl.so"
    "lib/libbatterylistener.so"
    "lib/vendor.qti.hardware.servicetracker@1.0.so"
    "lib/vendor.qti.hardware.servicetracker@1.1.so"
    "lib/vendor.qti.hardware.servicetracker@1.2.so"
    "lib/vendor.qti.hardware.systemhelper@1.0.so"
    "lib64/android.hardware.automotive.vehicle@2.0-manager-lib.so"
    "lib64/carwatchdog_aidl_interface-V2-ndk_platform.so"
    "lib64/com.dsi.ant@1.0.so"
    "lib64/hw/android.hardware.health@2.0-impl-2.1.so"
    "lib64/hw/vendor.qti.hardware.servicetracker@1.2-impl.so"
    "lib64/libbatterylistener.so"
    "lib64/vendor.qti.hardware.fstman@1.0.so"
    "lib64/vendor.qti.hardware.servicetracker@1.0.so"
    "lib64/vendor.qti.hardware.servicetracker@1.1.so"
    "lib64/vendor.qti.hardware.servicetracker@1.2.so"
    "lib64/vendor.qti.hardware.systemhelper@1.0.so"
    "lib64/vendor.qti.hardware.vibrator.impl.so"

    # Overlays
    "overlay/FrameworksResTarget.apk"
    "overlay/WifiResTarget.apk"

    # Permisssions
    "etc/a2dp_audio_policy_configuration.xml"
    "etc/audio_effects_ZS670KS.xml"
    "etc/audio_effects.xml"
    "etc/audio_io_policy_ZS670KS.conf"
    "etc/audio_io_policy.conf"
    "etc/audio_platform_info_intcodec_ZS670KS.xml"
    "etc/audio_platform_info_intcodec.xml"
    "etc/audio_policy_configuration.xml"
    "etc/audio_policy_volumes.xml"
    "etc/audio_tuning_mixer.txt"
    "etc/bluetooth_audio_policy_configuration.xml"
    "etc/bluetooth_qti_hearing_aid_audio_policy_configuration.xml"
    "etc/default_volume_tables.xml"
    "etc/media_codecs_c2.xml"
    "etc/media_codecs_google_audio.xml"
    "etc/media_codecs_google_c2_audio.xml"
    "etc/media_codecs_google_c2_video.xml"
    "etc/media_codecs_google_c2.xml"
    "etc/media_codecs_google_telephony.xml"
    "etc/media_codecs_google_video_le.xml"
    "etc/media_codecs_google_video.xml"
    "etc/media_codecs_kona.xml"
    "etc/media_codecs_performance_kona.xml"
    "etc/media_codecs_performance.xml"
    "etc/media_codecs_vendor_audio.xml"
    "etc/media_codecs_vendor.xml"
    "etc/media_codecs.xml"
    "etc/media_profiles_kona.xml"
    "etc/media_profiles_vendor.xml"
    "etc/media_profiles.xml"
    "etc/mixer_paths.xml"
    "etc/permissions/android.hardware.audio.low_latency.xml"
    "etc/permissions/android.hardware.audio.pro.xml"
    "etc/permissions/android.hardware.bluetooth_le.xml"
    "etc/permissions/android.hardware.bluetooth.xml"
    "etc/permissions/android.hardware.camera.flash-autofocus.xml"
    "etc/permissions/android.hardware.camera.front.xml"
    "etc/permissions/android.hardware.camera.full.xml"
    "etc/permissions/android.hardware.camera.raw.xml"
    "etc/permissions/android.hardware.fingerprint.xml"
    "etc/permissions/android.hardware.location.gps.xml"
    "etc/permissions/android.hardware.nfc.hce.xml"
    "etc/permissions/android.hardware.nfc.hcef.xml"
    "etc/permissions/android.hardware.nfc.xml"
    "etc/permissions/android.hardware.opengles.aep.xml"
    "etc/permissions/android.hardware.se.omapi.uicc.xml"
    "etc/permissions/android.hardware.sensor.accelerometer.xml"
    "etc/permissions/android.hardware.sensor.compass.xml"
    "etc/permissions/android.hardware.sensor.gyroscope.xml"
    "etc/permissions/android.hardware.sensor.light.xml"
    "etc/permissions/android.hardware.sensor.proximity.xml"
    "etc/permissions/android.hardware.sensor.stepcounter.xml"
    "etc/permissions/android.hardware.sensor.stepdetector.xml"
    "etc/permissions/android.hardware.telephony.gsm.xml"
    "etc/permissions/android.hardware.telephony.ims.xml"
    "etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml"
    "etc/permissions/android.hardware.usb.accessory.xml"
    "etc/permissions/android.hardware.usb.host.xml"
    "etc/permissions/android.hardware.vulkan.compute-0.xml"
    "etc/permissions/android.hardware.vulkan.level-1.xml"
    "etc/permissions/android.hardware.vulkan.version-1_1.xml"
    "etc/permissions/android.hardware.wifi.aware.xml"
    "etc/permissions/android.hardware.wifi.direct.xml"
    "etc/permissions/android.hardware.wifi.passpoint.xml"
    "etc/permissions/android.hardware.wifi.rtt.xml"
    "etc/permissions/android.hardware.wifi.xml"
    "etc/permissions/android.software.device_id_attestation.xml"
    "etc/permissions/android.software.ipsec_tunnels.xml"
    "etc/permissions/android.software.midi.xml"
    "etc/permissions/android.software.sip.voip.xml"
    "etc/permissions/android.software.verified_boot.xml"
    "etc/permissions/com.android.nfc_extras.xml"
    "etc/permissions/com.nxp.mifare.xml"
    "etc/r_submix_audio_policy_configuration.xml"
    "etc/sound_trigger_mixer_paths.xml"
    "etc/sound_trigger_platform_info.xml"
    "etc/usb_audio_policy_configuration.xml"
    "etc/wifi/p2p_supplicant_overlay.conf"
    "etc/wifi/qca6390/WCNSS_qcom_cfg.ini"
    "etc/wifi/wpa_supplicant_overlay.conf"

    # Power
    "bin/hw/android.hardware.power-service"
    "etc/init/android.hardware.power-service.rc"
    "etc/vintf/manifest/power.xml"
    "lib/vendor.qti.hardware.perf@2.0.so"
    "lib64/vendor.qti.hardware.perf@2.0.so"

    # QMI
    "lib/libjson.so"
    "lib/libqti_vndfwk_detect.so"
    "lib/libvndfwk_detect_jni.qti.so"
    "lib64/libjson.so"
    "lib64/libqti_vndfwk_detect.so"
    "lib64/libvndfwk_detect_jni.qti.so"

    # Region specific build.prop
    "build_eu.prop"
    "build_ru_0.prop"
    "build_ru_1.prop"

    # RIL
    "lib/libprotobuf-cpp-full-3.9.1.so"
    "lib/libprotobuf-cpp-lite-3.9.1.so"
    "lib/libreference-ril.so"
    "lib/libril.so"
    "lib/librilutils.so"
    "lib/librmnetctl.so"
    "lib64/libnetfilter_conntrack.so"
    "lib64/libnfnetlink.so"
    "lib64/libprotobuf-cpp-full-3.9.1.so"
    "lib64/libprotobuf-cpp-lite-3.9.1.so"
    "lib64/libreference-ril.so"
    "lib64/libril.so"
    "lib64/librilutils.so"
    "lib64/librmnetctl.so"

    # Rootdir
    "etc/fstab.qcom"
    "etc/init/hw/init.asus.usb.rc"
    "etc/init/hw/init.qcom.factory.rc"
    "etc/init/hw/init.qcom.rc"
    "etc/init/hw/init.target.rc"

    # Sensors
    # Use prebuilt init.rc which starts the hal with group `input`
    # "etc/init/android.hardware.sensors@2.0-service-multihal.rc"
    "bin/hw/android.hardware.sensors@2.0-service.multihal"
    "etc/vintf/manifest/android.hardware.sensors@2.0-multihal.xml"
    "lib/android.hardware.sensors@2.0-ScopedWakelock.so"
    "lib64/android.hardware.sensors@2.0-ScopedWakelock.so"
    "lib64/libsensorndkbridge.so"

    # Sepolicy
    "etc/selinux/plat_pub_versioned.cil"
    "etc/selinux/plat_sepolicy_vers.txt"
    "etc/selinux/selinux_denial_metadata"
    "etc/selinux/vendor_file_contexts"
    "etc/selinux/vendor_hwservice_contexts"
    "etc/selinux/vendor_mac_permissions.xml"
    "etc/selinux/vendor_property_contexts"
    "etc/selinux/vendor_seapp_contexts"
    "etc/selinux/vendor_sepolicy.cil"
    "etc/selinux/vendor_service_contexts"
    "etc/selinux/vndservice_contexts"

    # SLA Dual Network
    "app/slaservice/slaservice.apk"
    "bin/hw/vendor.qti.sla.service@1.0-service"
    "bin/slad"
    "etc/init/slad.rc"
    "etc/init/vendor.qti.sla.service@1.0-service.rc"
    "etc/sla/slad_data_iface.conf"
    "etc/sla/slad_num_iface.conf"
    "etc/sla/slad.conf"
    "etc/sla/slm_supported_list.xml"
    "etc/sla/slmAppUseCase.conf"
    "lib/hw/vendor.qti.sla.service@1.0-impl.so"
    "lib/vendor.qti.sla.service@1.0.so"
    "lib64/hw/vendor.qti.sla.service@1.0-impl.so"
    "lib64/vendor.qti.sla.service@1.0.so"

    # Symlinks
    "app/CneApp/lib/arm64/libvndfwk_detect_jni.qti.so"
    "asusfw"
    "factory"
    "firmware/wlan/qca_cld/COUNTRY"
    "firmware/wlan/qca_cld/qca6390/wlan_mac.bin"
    "firmware/wlan/qca_cld/qca6490/wlan_mac.bin"
    "lib/libEGL_adreno.so"
    "lib/libGLESv2_adreno.so"
    "lib/libq3dtools_adreno.so"
    "lib64/libEGL_adreno.so"
    "lib64/libGLESv2_adreno.so"
    "lib64/libq3dtools_adreno.so"
    "odm"
    "rfs/apq/gnss/hlos"
    "rfs/apq/gnss/ramdumps"
    "rfs/apq/gnss/readonly/firmware"
    "rfs/apq/gnss/readonly/vendor/firmware"
    "rfs/apq/gnss/readwrite"
    "rfs/apq/gnss/shared"
    "rfs/mdm/adsp/hlos"
    "rfs/mdm/adsp/ramdumps"
    "rfs/mdm/adsp/readonly/firmware"
    "rfs/mdm/adsp/readonly/vendor/firmware"
    "rfs/mdm/adsp/readwrite"
    "rfs/mdm/adsp/shared"
    "rfs/mdm/cdsp/hlos"
    "rfs/mdm/cdsp/ramdumps"
    "rfs/mdm/cdsp/readonly/firmware"
    "rfs/mdm/cdsp/readwrite"
    "rfs/mdm/cdsp/shared"
    "rfs/mdm/mpss/hlos"
    "rfs/mdm/mpss/ramdumps"
    "rfs/mdm/mpss/readonly/firmware"
    "rfs/mdm/mpss/readonly/vendor/firmware"
    "rfs/mdm/mpss/readwrite"
    "rfs/mdm/mpss/shared"
    "rfs/mdm/slpi/hlos"
    "rfs/mdm/slpi/ramdumps"
    "rfs/mdm/slpi/readonly/firmware"
    "rfs/mdm/slpi/readwrite"
    "rfs/mdm/slpi/shared"
    "rfs/mdm/tn/hlos"
    "rfs/mdm/tn/ramdumps"
    "rfs/mdm/tn/readonly/firmware"
    "rfs/mdm/tn/readwrite"
    "rfs/mdm/tn/shared"
    "rfs/msm/adsp/hlos"
    "rfs/msm/adsp/ramdumps"
    "rfs/msm/adsp/readonly/firmware"
    "rfs/msm/adsp/readonly/vendor/firmware"
    "rfs/msm/adsp/readwrite"
    "rfs/msm/adsp/shared"
    "rfs/msm/cdsp/hlos"
    "rfs/msm/cdsp/ramdumps"
    "rfs/msm/cdsp/readonly/firmware"
    "rfs/msm/cdsp/readonly/vendor/firmware"
    "rfs/msm/cdsp/readwrite"
    "rfs/msm/cdsp/shared"
    "rfs/msm/mpss/hlos"
    "rfs/msm/mpss/ramdumps"
    "rfs/msm/mpss/readonly/firmware"
    "rfs/msm/mpss/readonly/vendor/firmware"
    "rfs/msm/mpss/readwrite"
    "rfs/msm/mpss/shared"
    "rfs/msm/slpi/hlos"
    "rfs/msm/slpi/ramdumps"
    "rfs/msm/slpi/readonly/firmware"
    "rfs/msm/slpi/readonly/vendor/firmware"
    "rfs/msm/slpi/readwrite"
    "rfs/msm/slpi/shared"

    # Toybox
    "bin/acpi"
    "bin/base64"
    "bin/basename"
    "bin/blockdev"
    "bin/cal"
    "bin/cat"
    "bin/chattr"
    "bin/chcon"
    "bin/chgrp"
    "bin/chmod"
    "bin/chown"
    "bin/chroot"
    "bin/chrt"
    "bin/cksum"
    "bin/clear"
    "bin/cmp"
    "bin/comm"
    "bin/cp"
    "bin/cpio"
    "bin/cut"
    "bin/date"
    "bin/dd"
    "bin/devmem"
    "bin/df"
    "bin/diff"
    "bin/dirname"
    "bin/dmesg"
    "bin/dos2unix"
    "bin/du"
    "bin/echo"
    "bin/egrep"
    "bin/env"
    "bin/expand"
    "bin/expr"
    "bin/fallocate"
    "bin/false"
    "bin/fgrep"
    "bin/file"
    "bin/find"
    "bin/flock"
    "bin/fmt"
    "bin/free"
    "bin/fsync"
    "bin/getconf"
    "bin/getenforce"
    "bin/getevent"
    "bin/getprop"
    "bin/groups"
    "bin/gunzip"
    "bin/gzip"
    "bin/head"
    "bin/hostname"
    "bin/hwclock"
    "bin/i2cdetect"
    "bin/i2cdump"
    "bin/i2cget"
    "bin/i2cset"
    "bin/iconv"
    "bin/id"
    "bin/ifconfig"
    "bin/inotifyd"
    "bin/insmod"
    "bin/install"
    "bin/ionice"
    "bin/iorenice"
    "bin/kill"
    "bin/killall"
    "bin/ln"
    "bin/load_policy"
    "bin/log"
    "bin/logname"
    "bin/losetup"
    "bin/ls"
    "bin/lsattr"
    "bin/lsmod"
    "bin/lsof"
    "bin/lspci"
    "bin/lsusb"
    "bin/md5sum"
    "bin/microcom"
    "bin/mkdir"
    "bin/mkfifo"
    "bin/mknod"
    "bin/mkswap"
    "bin/mktemp"
    "bin/modinfo"
    "bin/modprobe"
    "bin/more"
    "bin/mount"
    "bin/mountpoint"
    "bin/mv"
    "bin/nc"
    "bin/netcat"
    "bin/netstat"
    "bin/nice"
    "bin/nl"
    "bin/nohup"
    "bin/nproc"
    "bin/nsenter"
    "bin/od"
    "bin/paste"
    "bin/patch"
    "bin/pgrep"
    "bin/pidof"
    "bin/pkill"
    "bin/pmap"
    "bin/printenv"
    "bin/printf"
    "bin/ps"
    "bin/pwd"
    "bin/readelf"
    "bin/readlink"
    "bin/realpath"
    "bin/renice"
    "bin/restorecon"
    "bin/rm"
    "bin/rmdir"
    "bin/rmmod"
    "bin/runcon"
    "bin/sed"
    "bin/sendevent"
    "bin/seq"
    "bin/setenforce"
    "bin/setprop"
    "bin/setsid"
    "bin/sha1sum"
    "bin/sha224sum"
    "bin/sha256sum"
    "bin/sha384sum"
    "bin/sha512sum"
    "bin/sleep"
    "bin/sort"
    "bin/split"
    "bin/start"
    "bin/stat"
    "bin/stop"
    "bin/strings"
    "bin/stty"
    "bin/swapoff"
    "bin/swapon"
    "bin/sync"
    "bin/sysctl"
    "bin/tac"
    "bin/tail"
    "bin/tar"
    "bin/taskset"
    "bin/tee"
    "bin/test"
    "bin/time"
    "bin/timeout"
    "bin/top"
    "bin/touch"
    "bin/tr"
    "bin/true"
    "bin/truncate"
    "bin/tty"
    "bin/ulimit"
    "bin/umount"
    "bin/uname"
    "bin/uniq"
    "bin/unix2dos"
    "bin/unlink"
    "bin/unshare"
    "bin/uptime"
    "bin/usleep"
    "bin/uudecode"
    "bin/uuencode"
    "bin/uuidgen"
    "bin/vmstat"
    "bin/watch"
    "bin/wc"
    "bin/which"
    "bin/whoami"
    "bin/xargs"
    "bin/xxd"
    "bin/yes"
    "bin/zcat"

    # Utils
    "bin/applypatch"
    "bin/awk"
    "bin/boringssl_self_test32"
    "bin/boringssl_self_test64"
    "bin/checkpoint_gc"
    "bin/cplay"
    "bin/dumpsys"
    "bin/logwrapper"
    "bin/mm-vidc-omx-test"
    "bin/sh"
    "bin/wpa_cli"
    "etc/init/boringssl_self_test.rc"
    "etc/init/vendor_flash_recovery.rc"
    "etc/mkshrc"

    # VNDK
    "bin/vndservice"
    "bin/vndservicemanager"
    "etc/init/vndservicemanager.rc"
    "etc/vintf/manifest/manifest.xml"
    "lib/libgui_vendor.so"
    "lib/libhidltransport.so"
    "lib/libhwbinder.so"
    "lib64/libhidltransport.so"
    "lib64/libhwbinder.so"
    "lib64/libhwminijail.so"

    # Wifi
    "bin/hostapd_cli"
    "bin/hw/android.hardware.wifi@1.0-service"
    "bin/hw/hostapd"
    "bin/hw/vendor.asus.wifi.netutil@1.0-service"
    "bin/hw/wpa_supplicant"
    "etc/init/android.hardware.wifi@1.0-service.rc"
    "etc/init/hostapd.android.rc"
    "etc/init/vendor.asus.wifi.netutil@1.0-service.rc"
    "etc/vintf/manifest/android.hardware.wifi.hostapd.xml"
    "etc/vintf/manifest/android.hardware.wifi@1.0-service.xml"
    "lib/libcld80211.so"
    "lib/libwifi-hal-ctrl.so"
    "lib/libwifi-hal-qcom.so"
    "lib/libwpa_client.so"
    "lib64/libcld80211.so"
    "lib64/libkeystore-engine-wifi-hidl.so"
    "lib64/libkeystore-wifi-hidl.so"
    "lib64/libwifi-hal-ctrl.so"
    "lib64/libwifi-hal-qcom.so"
    "lib64/libwifi-hal.so"
    "lib64/libwpa_client.so"
    "lib64/vendor.asus.wifi.netutil@1.0.so"
    "lib64/vendor.qti.hardware.wifi.hostapd@1.0.so"
    "lib64/vendor.qti.hardware.wifi.hostapd@1.1.so"
    "lib64/vendor.qti.hardware.wifi.hostapd@1.2.so"
    "lib64/vendor.qti.hardware.wifi.supplicant@2.0.so"
    "lib64/vendor.qti.hardware.wifi.supplicant@2.1.so"
)

generate_prop_list_from_image "$1" "$2" VENDOR_SKIP_FILES_DEVICE

# Fixups
_output_file=$2
function presign() {
    sed -i "s|vendor/$1$|vendor/$1;PRESIGNED|g" $_output_file
}
function as_module() {
    sed -i "s|vendor/$1$|-vendor/$1|g" $_output_file
}

as_module "etc/vintf/manifest/android.hardware.gnss@2.1-service-qti.xml"
as_module "etc/vintf/manifest/android.hardware.lights-qti.xml"
as_module "etc/vintf/manifest/android.hardware.neuralnetworks@1.3-service-qti-hta.xml"
as_module "etc/vintf/manifest/android.hardware.neuralnetworks@1.3-service-qti.xml"
as_module "etc/vintf/manifest/c2_manifest_vendor.xml"
as_module "etc/vintf/manifest/manifest_android.hardware.drm@1.3-service.widevine.xml"
as_module "etc/vintf/manifest/vendor.qti.gnss@4.0-service.xml"
as_module "lib/libfastcvopt.so"
as_module "lib/libthermalclient.so"
as_module "lib64/libfastcvopt.so"
as_module "lib64/libthermalclient.so"

header "# All blobs, unless pinned, are extracted from:\n# $BUILD_FINGERPRINT"